voting-app:
  build: ./voting-app/.
  ports:
  - "5000:80"
  links:
  - redis

result-app:
  build: ./result-app/.
  ports:
  - "5001:80"
  links:
  - db

worker:
  build: ./worker
  links:
  - db
  - redis

redis:
  image: hypriot/rpi-redis
  ports: ["6379"]

db:
  image: randyp/rpi-postgres


